### ISSUE TITLE
Prometheus Alertmanager integration

### ISSUE THREAD

**Issue by houqp** [linkedin/iris#110]

**Comment by jrgp** [comment]
This would be a good idea

**Comment by jrgp** [comment]
Looks like their client for pagerduty is hard-coded into their golang codebase.

We should probably write a golang client for iris, maybe keep it in the same repo as the python one (separate subfolder that's still `go get`-able.

**Comment by wleese** [comment]
Note that as per their documentation, they won't be accepting new receivers. Instead, they're betting on everything supporting a generic webhook.

**Comment by jrgp** [comment]
Closing this as wleese added this.
