### ISSUE TITLE
reject invalid `role:target` early in sender rpc handler

### ISSUE THREAD

**Issue by houqp** [linkedin/iris#128]
The current behavior is a little bit confusing because it returns 200 to the client, the message won't be delivered later in the code path if `role:target` is invalid.

**Comment by jrgp** [comment]
I can't reproduce this. When I try to send to an invalid user using iris.client, I get this:

```
ValueError: Error response from server, 400: {
    "title": "Request rejected by sender",
    "description": "INVALID role:target"
}
```

However, I did add tests and more logging to confirm this behavior, and added a few more checks that reject requests that are missing both body and template (which results in not being able to send a message anyway):

https://github.com/linkedin/iris/pull/130

**Comment by houqp** [comment]
Ha, you are right, I missed that extra expand check ;)
