### ISSUE TITLE
support deleting unused plans and templates

### ISSUE THREAD

**Issue by houqp** [linkedin/iris#169]

**Comment by jrgp** [comment]
This adds backend support: https://github.com/linkedin/iris/pull/208

**Comment by jrgp** [comment]
Need to add a button/modal to the plan editor that hits that new API endpoint

**Comment by jrgp** [comment]
UI PR: https://github.com/linkedin/iris/pull/209

**Comment by jrgp** [comment]
Both of those have been merged so closing.
