### ISSUE TITLE
css paths missing

### ISSUE THREAD

**Issue by kjetilmjos** [linkedin/iris#238]
Tried an installation of Iris and got it running, but there is no CSS displayed in the browser. Static logo is working. Tried looking a bit in the source code and the CSS link path is empty when I do inspect source, so my guess is that there is something wrong in the templating where it sais ASSET_URL. Not sure how to fix it though.

**Comment by dwang159** [comment]
Seems like an issue with webassets. How are you running Iris when you see this issue? Docker, Makefile?

**Comment by kjetilmjos** [comment]
I'm running it using make serve. Followed the setup in the readme file

**Comment by dwang159** [comment]
Does the src/iris/ui/bundles directory exist? In [src/iris/ui/\_\_init\_\_.py](https://github.com/linkedin/iris/blob/master/src/iris/ui/__init__.py#L22), the first few lines should create js and css bundles that the frontend can reference. Are you seeing any errors in creating bundles when running make?

**Comment by kjetilmjos** [comment]
The bundle directory is not in src/iris/ui/bundles but instead under src/iris/ui/static/bundles
Not seeing any error messages when running make serve. The following lines are printed:

[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Web asset root: "/home/ubuntu/iris/src/iris/ui"
[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Building bundle: bundles/iris.js
[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Building bundle: bundles/libs.css
[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Building bundle: bundles/iris.css
[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Building bundle: bundles/jquery.libs.js
[2017-07-12 13:32:22 +0000] [3274] [INFO] iris.ui Building bundle: bundles/bootstrap.libs.js

Could there be a path mismatch somewhere?

**Comment by houqp** [comment]
The bundles should be generated at src/iris/ui/static/bundles, see: https://github.com/linkedin/iris/blob/master/src/iris/ui/__init__.py#L25. Could check out the rendered html source to see what's the generated CSS link path?

**Comment by houqp** [comment]
@kjetilmjos could you tell us what OS are you using?

**Comment by houqp** [comment]
Could you also run `pip freeze` paste the content here?

**Comment by jrgp** [comment]
I wonder if this could be due to restrictive file permissions and webassets silently filing to write the files. 

What user are you running make serve as the same user you clone/installed the venv/etc ?

**Comment by kjetilmjos** [comment]
I'm runnning ubuntu 16.04 LTS on a virtualbox machine with python 2.7.12
Output of pip freeze:
adium-theme-ubuntu==0.3.4
alabaster==0.7.10
argh==0.26.2
Babel==2.4.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
Beaker==1.9.0
cached-property==1.3.0
certifi==2017.4.17
chardet==3.0.4
click==6.6
configparser==3.5.0
coverage==4.4.1
cssmin==0.2.0
dnspython==1.14.0
docutils==0.13.1
enum34==1.1.6
exchangelib==1.9.3
falcon==1.1.0
falcon-cors==1.1.2
flake8==3.3.0
funcsigs==1.0.2
future==0.16.0
gevent==1.2.2
google-api-python-client==1.4.2
greenlet==0.4.12
gunicorn==19.7.1
httplib2==0.10.3
idna==2.5
imagesize==0.7.1
importlib==1.0.3
-e git+https://github.com/linkedin/iris@4b603a94d0bd23e6f857ebd8ac14c630e605dd02#egg=iris
irisclient==1.2.0
Jinja2==2.9.6
kazoo==2.3.1
livereload==2.5.1
lxml==3.8.0
Markdown==2.4.1
MarkupSafe==1.0
mccabe==0.6.1
mock==2.0.0
msgpack-python==0.4.5
ntlm-auth==1.0.5
oauth2client==1.4.12
-e git+https://github.com/linkedin/oncall.git@f18141a0f3476fa5a31e1509110ff93d982e76c7#egg=oncall
ordereddict==1.1
pathtools==0.1.2
pbr==3.1.1
phonenumbers==8.5.2
pluggy==0.4.0
port-for==0.3.1
py==1.4.34
pyasn1==0.2.3
pyasn1-modules==0.0.9
pycodestyle==2.3.1
pycrypto==2.6.1
pyflakes==1.5.0
Pygments==2.2.0
PyMySQL==0.7.11
pytest==3.1.2
pytest-cov==2.5.1
pytest-mock==1.5.0
python-ldap==2.4.40
python-mimeparse==1.6.0
pytz==2017.2
PyYAML==3.12
requests==2.12.4
requests-ntlm==1.0.0
rsa==3.4.2
singledispatch==3.4.0.3
six==1.10.0
slackclient==1.0.6
snowballstemmer==1.2.1
Sphinx==1.5.6
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
SQLAlchemy==1.1.11
streql==3.0.2
tornado==4.5.1
tox==2.7.0
twilio==4.5.0
tzlocal==1.4
ujson==1.35
unity-lens-photos==1.0
uritemplate==3.0.0
urllib3==1.21.1
virtualenv==15.1.0
watchdog==0.8.3
webassets==0.12.1
websocket-client==0.44.0
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

have been using the same user yes. Tried to give all permission chmod 777 to the iris folder but it did not make any difference. When I inspect the source file in chrome after login I get a header section that looks like this: 

<head>
--
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="icon" href="/static/images/iris.png?v=2">
   <title>Iris</title>
   <link href="" rel="stylesheet">
   <link href="" rel="stylesheet">
   </head>

**Comment by kjetilmjos** [comment]
Did a clean install again on Ubuntu 17.04 following the readme. The CSS issue was not there anymore. Closing this issue.
