### ISSUE TITLE
Certificate error on https://iris.claims

### ISSUE THREAD

**Issue by lazzurs** [linkedin/iris#306]
Hello,

When trying to visit https://iris.claims I get a certificate error indicating the certificate in use is for *.github.com.

**Comment by fellyns** [comment]
Thanks for the report @lazzurs! - we'll get that fixed up as soon as we can. Until then feel free to use the http version to avoid the error.

**Comment by ChrisCarini** [comment]
Hey @fellyns ,
<img width="457" alt="screen shot 2019-01-06 at 10 59 48" src="https://user-images.githubusercontent.com/6374067/50740381-503c1600-11a2-11e9-8221-9d657df91174.png">
Cert seems good - I'm guessing this issue can be closed? :)

**Comment by lazzurs** [comment]
Yea cert is now good. Should have closed this sooner.
