### ISSUE TITLE
Missing documentation on the creation of Applications

### ISSUE THREAD

**Issue by wleese** [linkedin/iris#318]
It seems that there is no API documentation, UI or sample query that makes apparent how an application is created.

Any help would be appreciated.

**Comment by fellyns** [comment]
Hey @wleese - we have a microsite for Iris at http://iris.claims which has an example application integration (http://iris.claims/docs/nagios.html) does that help or were you looking for more information?

**Comment by wleese** [comment]
Not quite. I’m specifically looking for how application keys are created.

**Comment by dwang159** [comment]
Related to #281. Better docs are definitely needed for this setup. Applications can be created from the Iris frontend UI by any admin user (for example, the user "demo" in the dummy data). By logging in with an admin user, a "create application" button should appear in the top right of the Applications tab. This allows you to create an application and access its associated API key.
I'll try to expand on this blurb and give it a home in our official docs, but hopefully that should be enough to get you started.
