### ISSUE TITLE
How to add new vendor support e.g. Hipchat?

### ISSUE THREAD

**Issue by wleese** [linkedin/iris#321]
I've implemented Hipchat support (./src/iris/vendors/iris_hipchat.py), but actually integrating this into Iris and Oncall isn't obvious to me.

In Iris, I can add a new mode (through a DB edit) called "hipchat". This is reflected in all the expected places in the UI.

Making a similar change to Oncall, for example in the contact_mode table, does not propagate any changes to the UI. Can I safely assume this is work in progress or am I missing something?

**Comment by jrgp** [comment]
That should be all that's needed for it to work within iris. Would you be able to make a PR? :)

As for oncall, @dwang159 should be able to provide more context there.

**Comment by wleese** [comment]
https://github.com/linkedin/iris/pull/324

**Comment by jrgp** [comment]
I think this can be closed as the PR was merged. This will/might require a similar PR on Oncall's end but it should be done for iris.
