### ISSUE TITLE
Support oncall schedules that are not 24/7

### ISSUE THREAD

**Issue by wleese** [linkedin/iris#330]
At our company, we have the following use case:

- Alert is created
- If office hours, TeamA is notified
- If outside office hours, TeamB is notified

I've set this up in Iris with a plan that:
- In step 1 has 2 Notifications
- The first points to TeamA in oncall as primary
- The second points to TeamB in oncall as primary

In Oncall:
- TeamA has someone oncall during office hours
- TeamB has someone oncall outside of office hours.

This works, but results in notifications going to the plan creator:

```
You are receiving this as you created this plan and we can't resolve oncall-primary of TeamA at this time.
```

Now I could suppress this message by making some code changes, but before I take that route (and potentially lose visibility into actual issues resolving oncall-primaries), I'd like to know if there is better way to achieve what I want. 

Edit: alternatively, I could add a dummy user with the drop mode and use that to fill in the gaps in the calendar for both teams..

**Comment by dwang159** [comment]
How are you doing the role lookup for oncall-primary? If you're using Oncall, our workflow is to create a single team containing both A and B. Then, we create a rotating schedule that has TeamA on call in the day and TeamB on call at night. This makes the Iris plan pretty trivial, and concentrates the scheduling logic into Oncall.

**Comment by wleese** [comment]
Ah, this issue is obviously in the wrong project. Anyway..

> If you're using Oncall, our workflow is to create a single team containing both A and B.

This would be fairly elegant were it not that one of the teams, say TeamB, actually supports 10s of other teams. In practice, we have developer teams and operations teams. The operations teams support many developer teams - let's say the ratio is 10:1.

Adding the operations teams to all the developer teams they support, is possible, but a change in the operations team membership, would now require 10 developer teams to have to be changed.

Of course everything can be automated, but I'm looking for the most low maintenance solution, preferably something intuitive and within the current scope of Oncall and Iris.

**Comment by dwang159** [comment]
We actually have a feature in-flight for this kind of use-case in Oncall. We call it "team subscription", which lets a team in Oncall borrow another team's events and put them onto its calendar. This lets you have TeamA "subscribe" to TeamB's primary events, and have them appear on TeamA's calendar. Then, when you query Oncall for TeamA's current primary, TeamB's primary will appear.

The main thing missing there is UI support; there's not yet a way to add them in the frontend. I think the calendar display for subscribed events is a little rough around the edges as well, but I haven't been able to get the time to throw that together. I think I'll check in with our web dev and our designer at LinkedIn and see what they're thinking about it.

**Comment by wleese** [comment]
@dwang159 sounds like what I'm looking for. If the backend code is there already, I'll snoop around and see if I can get something usable out of it. I can wait for the frontend to catch up.

**Comment by wleese** [comment]
Just tested this - works perfectly. Thanks!
