### ISSUE TITLE
Plans for mobile

### ISSUE THREAD

**Issue by jmatsushita** [linkedin/iris#355]
I’ve been looking at your work on Iris in the mobile branch of the `iris` and `iris-relay` repo and I’ve been wondering what is planned for the future? 

If I understand correctly currently `iris-relay` can do SAML but in its mobile branch it would use the qrcode/mobile_key for authorization instead that is generated in `iris`'s mobile branch?

Seems that there's also work to register devices for push notifications, is there work being done on a mobile client?

**Comment by dwang159** [comment]
You're correct that we have a mobile client being worked on right now. Currently we're doing some internal testing of how the mobile app would burrow through our corporate network isolation. The QR code in Iris would likely provide a mechanism for a mobile app to connect to the correct instance of Iris, but we're shying away from using it for authentication to allow for easier re-auth. The SAML in Iris-relay should allow for SSO integration with the app. We're working on a hybrid Phonegap-based mobile client, but that work isn't yet available to the open-source community.

**Comment by jmatsushita** [comment]
Hi @dwang159 any updates on the mobile front?
