### ISSUE TITLE
Bug: Plans with a name containing a '/' character cannot be deleted or updated.

### ISSUE THREAD

**Issue by tvlieg** [linkedin/iris#400]
If a plan has a slash in its name, e.g. "test-name-with-/-character", it cannot be deleted. The DELETE http request fails, generating a 404:

Request URL: https://iris.dev.bol.io/v0/plans/test-name-with-/-character
Request method: DELETE
Status code: 404 Not Found

**Comment by dwang159** [comment]
Thanks for the report, we'll take a look.

**Comment by dwang159** [comment]
Looks like the issue here is that plan deletion is specified via plan_id, rather than name. You should do a DELETE on `/v0/plans/$plan_id` and give that a shot.

**Comment by tvlieg** [comment]
I should have added that I didn't use the api myself, but that the problem occurs using the normal Iris web-gui. So if a DELETE on `/v0/plans/<plan>` should be done using a plan_id, than I think the bug is that the web gui is using name rather than plan_id while deleting a plan.

**Comment by tvlieg** [comment]
I think I have fixed this issue with PR #401 . Tested it in our Iris instance.

**Comment by dwang159** [comment]
Merged #401
