### ISSUE TITLE
Message not created when incident created

### ISSUE THREAD

**Issue by Ozymandiiaz** [linkedin/iris#408]
i'am using irisclient python to create incident but there is no message created ( notification)

**Comment by Ozymandiiaz** [comment]
only incident that i created

**Comment by dwang159** [comment]
Messages will only be created for an incident if Iris-sender is running. Can you try doing a "make sender" or running sender.py in src/iris/bin?

**Comment by Ozymandiiaz** [comment]
i get the message know thx, but i don't have the email in my inbox even if the smtp server configuration is good and i get the status sent in message

**Comment by dwang159** [comment]
I'm guessing this is related to #410 , closing this and continuing there. If Iris is using the dummy vendor instead of SMTP, it's likely that all you need to do is reconfigure it to use the STMP vendor.
