### ISSUE TITLE
Custom Vendor for Sending Message and Notification

### ISSUE THREAD

**Issue by tsimyau1612** [linkedin/iris#425]
Hi, I would like to know if it's possible to add a custom vendor for sending message and notification. So far, Iris provides sending them via email, slack, and twillio. But what if I want to send the message and notification by firing a personalized API? If it's possible, where do I start and what do I have to add? Thanks in advance.

**Comment by dwang159** [comment]
Custom vendors are supported (for example, see the community-contributed messagebird vendor: https://github.com/linkedin/iris/blob/master/src/iris/vendors/iris_messagebird.py). You'll need to create a vendor class that defines a `supports` attribute, which defines what modes this vendor supports. Then, you need to define a `send()` function (e.g. https://github.com/linkedin/iris/blob/master/src/iris/vendors/iris_messagebird.py#L98), which can handle all the logic of calling your API to send the messages.

**Comment by dwang159** [comment]
You'll need to run the Iris sender for messages to send. `make sender` should do that in the dev environment. You don't actually need to define a new priority unless you want to; making it available as a contact mode is sufficient as long as users update their default priority -> mode settings.
