### ISSUE TITLE
400 when integrating with alertmanager

### ISSUE THREAD

**Issue by liuzhen** [linkedin/iris#479]
```
21/Jan/2019:10:53:02 +0000 [400] POST /v0/webhooks/alertmanager?application=alertmanager&key=066f66e751e47a1652ee3ae00cc5f4b282e151f78cb22d789486ac95bf9dea56 10.18.33.252 [Alertmanager/0.15.1] RT:1 REF:- SZ:227 HTTP/1.1
```

error.log says nothing of ERROR, and I cannot find any other than access.log / error.log

**Comment by liuzhen** [comment]
while that 400 is companied by "no iris_plan in groupLables", after we postman the request manually.

it will be better iris log it out though.

**Comment by pavanfhw** [comment]
@liuzhen thank you for posting the solution. It saved me some time.
