### ISSUE TITLE
Picking a commit to build a release is hard

### ISSUE THREAD

**Issue by avanier** [linkedin/iris#489]
Could it be possible to consider doing tagged releases? Right now, the current head as of f607fe4c5595469766470b899950d97570e8aebe cannot be built, and the latest image on Quay dates from 2017.

Would it be possible to tag what commits are actually buildable with [semantic versioning](https://semver.org/)?

**Comment by dwang159** [comment]
Good point. After #491 is merged, we can begin to tag releases and pair them with quay images.
