### ISSUE TITLE
Internal errors if ujson >= 2.x

### ISSUE THREAD

**Issue by dsanader** [linkedin/iris#569]
The same kind of errors are triggered in `api.py` on a new install when you click on menu buttons (Plans, Templates...), the root exception is :

```python
TypeError: <pymysql.cursors.SSDictCursor object at *> is not JSON serializable
```
Downgrading to usjon==1.35 helps.

Guess the generic serialization removal in [2.0.0](https://github.com/ultrajson/ultrajson/releases/tag/2.0.0) hurts.

**Comment by diegocepedaw** [comment]
Fixed in #[571](https://github.com/linkedin/iris/pull/571)
