### ISSUE TITLE
IRIS ldap not working 

### ISSUE THREAD

**Issue by JTS911** [linkedin/iris#655]
Hi All 

We changed companies and I had to change the ldap integration from old AD to new AD. I changed the following files and configs 

/opt/oncall/configs/config.yaml
  ldap_url: 'ldap://<correct IP>'
  ldap_user_suffix: ''
  ldap_bind_user: 'XXXXX'
  ldap_bind_password: 'XXXX'
  ldap_base_dn: 'XXXXX'
  ldap_search_filter: '(sAMAccountName=%s)'
 
ldap_sync:
  url: 'ldap://<correct IP>'

/opt/iris/configs/config.dev.yaml

  ldap_url: 'ldap://<correct IP>'
  ldap_user_suffix: ''
  ldap_cert_path: '/opt/'
  ldap_bind_user: 'xxxxxx'
  ldap_bind_password: 'xxxxxx'
  ldap_base_dn: 'xxxxxx'
  ldap_search_filter: '(sAMAccountName=%s)'

OnCall works and I can sync the users (new users are in OnCall with all detail from new company ) 
Also able to use new AD username and password for OnCall, but IRIS does not want to authenticate.
error message: Invalid credentials

I can run a ldapsearch -H ldap://xxxx and get results back, 

So OnCall can authenticate but not IRIS 

Any suggestions PLEASE  ?

**Comment by baryluk** [comment]
I would suggest putting explicit port number int he ldap_url. for example `ldap://foo.example.com:389/`
   (same with ldaps and 636).

This solved some issues for me in the past.

**Comment by JTS911** [comment]
> I would suggest putting explicit port number int he ldap_url. for example `ldap://foo.example.com:389/` (same with ldaps and 636).
> 
> This solved some issues for me in the past.

Thanks for the suggestion, it did not do the trick

**Comment by JTS911** [comment]
It was yaml malformed file
