### ISSUE TITLE
Hello! How to connect AVAX to METAMASK?

### ISSUE THREAD

**Issue by Irishgrizz** [linkedin/iris#670]
Hello! How to connect AVAX to METAMASK?

__Originally posted by @Bumblebee9999 in https://github.com/ethereum-lists/chains/issues/512#issuecomment-950330951__

**Comment by Irishgrizz** [comment]
Bye-bye now bumblebee fucking Trash

**Comment by diegocepedaw** [comment]
This is the github page for Iris, closing since this is unrelated
